### ISSUE TITLE
5-year retrospect article

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#70]
Solidity 0.1.0 will be 5 years on the 10th of July.

Perhaps it is worth commemorating this with some retrospect how the project, team, language, and ecosystem has changed over time?

May be combined with #69.

@chriseth @franzihei opinion?

**Comment by franzihei** [comment]
I like the idea of a 5-year retro / anniversary post! I like it more than the individual post about the team.

**Comment by franzihei** [comment]
I put a rough outline where we can collect ideas for the storyline and talking points here: https://hackmd.io/@franzihei/rJH5Q462I

**Comment by franzihei** [comment]
I finished the write up for the birthday post! --> https://hackmd.io/@franzihei/rJH5Q462I
@chriseth please have a look at the contributors list and feel free to adjust it.
@axic I prepared the post to be ready before I go on holiday, I tried to put your slide content into words (plus some graphics for the timeline), because I think it was very fitting for the post. I hope you're ok with it, please take a look!

**Comment by franzihei** [comment]
PR is ready incl. instructions (because I will be on holidays). Also, here is the doc of the roadmap in case anything needs last minute changing in the graphics: https://docs.google.com/presentation/d/1dRK0OMse-MExwBtEtkANhwgq2Uhc61rWgFrVhxMup2I/edit#slide=id.g8aa74b1c17_0_2474
